### ISSUE TITLE
java.lang.RuntimeException: General Error on signed upload with chunk_size option

### ISSUE THREAD

**Issue by dimaportenko** [cloudinary/cloudinary_android#148]
When the size of the uploading file is bigger then `chunk_size` option I'm getting the following error 
```
java.lang.RuntimeException: General Error
at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:145)
at com.cloudinary.Uploader.callApi(Uploader.java:34)
at com.cloudinary.Uploader.uploadLargeParts(Uploader.java:218)
at com.cloudinary.Uploader.uploadLarge(Uploader.java:149)
at com.cloudinary.android.DefaultRequestProcessor.doProcess(DefaultRequestProcessor.java:223)
at com.cloudinary.android.DefaultRequestProcessor.processRequest(DefaultRequestProcessor.java:87)
at com.cloudinary.android.MediaManager.processRequest(MediaManager.java:441)
at com.cloudinary.android.AndroidJobStrategy$UploadJob.onRunJob(AndroidJobStrategy.java:264)
at com.evernote.android.job.Job.runJob(Job.java:124)
at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:183)
at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:168)
at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:151)
                                                                                                    	```

I'm using android SDK in this lib https://github.com/gosourcellc/react-native-cloudinary-sdk. Right now it uses 100mb chunk_size to overcome this issue.

**Comment by dimaportenko** [comment]
I can confirm there is no such method `upload_large`. I searched for it but had no luck. 
- Here the link you send me
![CleanShot 2022-09-21 at 18 51 28@2x](https://user-images.githubusercontent.com/6594232/191552216-8412a1b1-8f6f-483f-9daf-5e9cacdfdb43.png)
- here is android studio
<img width="713" alt="CleanShot 2022-09-21 at 18 48 20@2x" src="https://user-images.githubusercontent.com/6594232/191552387-b2aa9539-c573-42c4-9383-fe62dfe6e761.png">

here is [sdk source code](https://github.com/cloudinary/cloudinary_android/blob/master/core/src/main/java/com/cloudinary/android/MediaManager.java)

**Comment by dimaportenko** [comment]
Please check my source code (upload method) and help me to apply `upload_large` https://github.com/gosourcellc/react-native-cloudinary-sdk/blob/main/android/src/main/java/com/reactnativecloudinarysdk/CloudinarySdkModule.java

**Comment by dimaportenko** [comment]
Also, I'm using files less than 100MB.

**Comment by adimiz1** [comment]
Hi @dimaportenko 
Thank you very much for reporting this issue.
Can you please try to run your code with the following:
```MediaManager.get().getCloudinary().uploader().uploadLarge(file, options)```

**Comment by dimaportenko** [comment]
Ok, I think I was able to do upload like this
```
try {
        Map resultData = MediaManager.get().getCloudinary().uploader().uploadLarge(file, options, new ProgressCallback() {
          @Override
          public void onProgress(long bytesUploaded, long totalBytes) {
                // ....
          }
        });
        promise.resolve(Utils.mapToWritableMap(resultData));
      } catch (IOException exception) {
        promise.reject(exception.getMessage());
      }

```

How can I get `requesId` here? I would like to be able to cancel https://cloudinary.com/documentation/android_image_and_video_upload#cancel_an_upload
```
MediaManager.get().cancelRequest(requestId);
```

**Comment by tommyg-cld** [comment]
Hi @dimaportenko , the request id should be included in the response header we send back. 

Please let me know if you have any other questions or queries.

Kind Regards,
Thomas

**Comment by dimaportenko** [comment]
@tommyg-cld can you share a code sample? Not sure how to use it. And I'm not able to find it in the documentation.

**Comment by tommyg-cld** [comment]
@dimaportenko so you will need to use the dispatch method and this should return the request id per https://cloudinary.com/documentation/android_image_and_video_upload#mediamanager_upload_method

e.g. `String requestId = MediaManager.get().upload("imageFile.jpg").dispatch();`

**Comment by dimaportenko** [comment]
@tommyg-cld I'm completely confused. I'm this one
```
String requestId = MediaManager.get().upload("imageFile.jpg").dispatch();
```
but I have the error, please see the first message of the thread. And you asked me to use https://cloudinary.com/documentation/upload_images#chunked_asset_upload which doesn't exist. Then @adimiz1 said I have to use
```
MediaManager.get().getCloudinary().uploader().uploadLarge(file, options)
```
It works for upload but there is no request Id. So I can't cancel it. Please help me, I don't understand

**Comment by tommyg-cld** [comment]
@dimaportenko apologies, that was just an example,

does the below work?

`String requestId = MediaManager.get().getCloudinary().uploader().uploadLarge(file, options).dispatch();`

**Comment by dimaportenko** [comment]
Nope. 
`uploadLarge` return `Map` and it hasn't `dispatch` method.

**Comment by dimaportenko** [comment]
Also, this one isn't working for signed request 
```
MediaManager.get().getCloudinary().uploader().uploadLarge(file, options)
```

**Comment by tommyg-cld** [comment]
@dimaportenko let me check internally with the team and will get back to you.

**Comment by dimaportenko** [comment]
So I did more testing and I can confirm that unsigned upload works just fine. But signed request gives me a general error from the original message of this GitHub issue. It's same for 
```
MediaManager.get().getCloudinary().uploader().uploadLarge(file, options)
```

The error message doesn't give any tips. Can you help me with what is wrong here?
```
java.lang.RuntimeException: General Error
```

**Comment by tommyg-cld** [comment]
@dimaportenko apologies for the delay in getting back. 

So right now dispatch is not supported with upload_large, the request-id will only return when using the MediaManager object to upload. e.g.

`MediaManager.get().upload("imageFile.jpg").dispatch();`

We are checking further if we can support it.

Regarding the general error, please could you give us exactly how you sign your requests? I'm seeing a NoMethodError exception in our logs.

Also incase you didn't read it yet, here is how to setup signed upload: https://cloudinary.com/documentation/android_image_and_video_upload#signed_upload

**Comment by tommyg-cld** [comment]
@dimaportenko we are taking a look so will get back asap.

**Comment by tamaracloudinary** [comment]
Hi @dimaportenko, 

Can you please open a support ticket here: https://support.cloudinary.com/hc/en-us/requests/new with your cloud name and include more information on this? 

This is what we know so far:
1. You are trying to develop the SDK for React native using our Android SDK
2. You are trying to upload a large file (less than 100 MB)
3. You are trying to sign the request (please share with us how do you do that in your ticket).

In order for us to be able to reproduce the issue, we need every piece of information.
Once you open that ticket with more info, we will be able to escalate it internally.
Please confirm that what we understand is correct - that you try to create a React Native library using our Android SDK (this might be important for the solution).

We are waiting for your ticket,
Thanks a lot,
Tamara

**Comment by dimaportenko** [comment]
Hi there, any updates?

**Comment by rnamba-cloudinary** [comment]
Hey @dimaportenko,

We're still waiting on news from the internal team. Could you follow up on a ticket for this issue so we can keep the line of communication open there?

**Comment by dimaportenko** [comment]
> We're still waiting on news from the internal team.

It's already a month passed already and no updates. It doesn't look like anybody working on this issue. 

> Could you follow up on a ticket for this issue so we can keep the line of communication open there?

I didn't get any updates there, doesn't look helpful to me.

**Comment by tamaracloudinary** [comment]
Hi @dimaportenko, I replied to the ticket you opened. 
Let's continue this thread there.

**Comment by tommyg-cld** [comment]
@dimaportenko just following up to see if this is still an issue? let me know if its ok to close out.

**Comment by dimaportenko** [comment]
@tommyg-cld the issue is still the same. From internal support discussion, it's related to the `callback_url` and 

> The iOS SDK sends a header called X-Requested-With with the value XMLHttpRequest while the Android SDK does not. When using the callback parameter, that is only honoured for requests that aren't XHR-based (i.e. XMLHttpRequest). This is why the uploads redirect on Android but not on iOS. If the callback parameter was not being utilised then requests from both SDKs would not need to redirect as that won't be relevant anymore.

I suggest the following if you are going to add a solution like `add header  X-Requested-With with the value XMLHttpRequest to the Android SDK`. then you can close after the change. In case you are not going to fix it you can also close it, so it will not bother you.

**Comment by tommyg-cld** [comment]
@dimaportenko thx for the update, yes we have an internal ticket to `add header  X-Requested-With with the value XMLHttpRequest to the Android SDK` so we will keep you posted.
