### ISSUE TITLE
com.evernote:android-job makes app crash after reboot in Android N

### ISSUE THREAD

**Issue by Andoctorey** [cloudinary/cloudinary_android#29]
This library used in cloudinary library
`09-15 23:18:33.956 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.*, PID: 3264
                                     java.lang.RuntimeException: Unable to start receiver com.evernote.android.job.JobBootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.*/com.evernote.android.job.JobRescheduleService (has extras) }: app is in background uid UidRecord{3055e95 u0a114 RCVR idle procs:1 seq(0,0,0)}
                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
                                         at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                         at android.os.Looper.loop(Looper.java:164)
                                         at android.app.ActivityThread.main(ActivityThread.java:6541)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                      Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.*/com.evernote.android.job.JobRescheduleService (has extras) }: app is in background uid UidRecord{3055e95 u0a114 RCVR idle procs:1 seq(0,0,0)}
                                         at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                         at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                         at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                         at com.evernote.android.job.WakeLockUtil.startWakefulService(WakeLockUtil.java:95)
                                         at com.evernote.android.job.JobRescheduleService.startService(JobRescheduleService.java:24)
                                         at com.evernote.android.job.JobManager.<init>(JobManager.java:191)
                                         at com.evernote.android.job.JobManager.create(JobManager.java:114)
                                         at com.evernote.android.job.JobBootReceiver.onReceive(JobBootReceiver.java:49)
                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
                                         at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                         at android.os.Looper.loop(Looper.java:164) 
                                         at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-15 23:18:34.448 I/ActivityManager: Showing crash dialog for package com.* u0`

**Comment by idobarnoam** [comment]
Hi @Andoctorey
 
[Android Oreo](https://developer.android.com/about/versions/oreo/background.html) (which was released a couple of weeks ago) has a lot of restrictions on background processing. [Evernote](https://github.com/evernote/android-job/wiki/Version-1.2.0-and-Android-O) already has a fix but it's not released yet (RC status). Once they release, we'll release an update too.

Please note: the SDK works in Android Oreo. The only way to get this exception is to compile and target an app specifically for Android Oreo. 
In terms of an immediate workaround, there are two options:
1. Wait for the next SDK release. This depends largely on Evernote.
2. Target the App for Android Nougat (or earlier). The app will work on Oreo then - But it won't be possible to use the new Oreo features in the app.

**Comment by Andoctorey** [comment]
Thanks for reply, will use third option: lower version of cloudinary lib.

**Comment by idobarnoam** [comment]
@Andoctorey  Thanks for the update.
I'm closing this issue, but please re-open it if you have any questions.

**Comment by carloshwa** [comment]
Evernote has released 1.2.0, can you update Cloudinary please?

**Comment by MaorGariv** [comment]
Hi @carloshwa,

Thanks for that. We plan to release an update this week:)

Will let you know once it's published.

**Comment by nitzanj** [comment]
This was fixed in our latest release, no workarounds are necessary anymore.
