### ISSUE TITLE
I got a RuntimeException: Invalid Content-Range header

### ISSUE THREAD

**Issue by louistsaitszho** [cloudinary/cloudinary_android#32]
```
10-11 16:56:55.199 1115-2064/{applicationId} E/DefaultRequestProcessor: Unexpected exception for request {36 char here}.
                                                                                        java.lang.RuntimeException: Invalid Content-Range header
                                                                                            at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:143)
                                                                                            at com.cloudinary.Uploader.callApi(Uploader.java:34)
                                                                                            at com.cloudinary.Uploader.uploadLargeParts(Uploader.java:212)
                                                                                            at com.cloudinary.Uploader.uploadLarge(Uploader.java:143)
                                                                                            at com.cloudinary.android.DefaultRequestProcessor.doProcess(DefaultRequestProcessor.java:197)
                                                                                            at com.cloudinary.android.DefaultRequestProcessor.processRequest(DefaultRequestProcessor.java:89)
                                                                                            at com.cloudinary.android.MediaManager.processRequest(MediaManager.java:367)
                                                                                            at com.cloudinary.android.AndroidJobStrategy$UploadJob.onRunJob(AndroidJobStrategy.java:203)
                                                                                            at com.evernote.android.job.Job.runJob(Job.java:109)
                                                                                            at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:151)
                                                                                            at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:136)
                                                                                            at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:119)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                            at java.lang.Thread.run(Thread.java:818)
```

This happens when I am trying to upload a photo to clouding. I have implemented cloudinary for a few weeks now and this is the first time I see this exception.

Thanks!

**Comment by yakirp** [comment]
Hi @louistsaitszho , Does it happen to a specific resource (photo) you are trying to upload?

**Comment by louistsaitszho** [comment]
Probably not, since the photo is fresh from the camera (and then I pass the Uri for upload). So far it happens only on 1 device (Nexus 5 Marshmallow)

**Comment by louistsaitszho** [comment]
Update: switch the locale from arabic (ar_something) to english (en_US) and everything works fine!?

**Comment by yakirp** [comment]
@louistsaitszho Thank you for pointing this out! I will check this with the team.

**Comment by MaxBayne** [comment]
@yakirp 
any help for this issue

thanks

**Comment by yakirp** [comment]
@louistsaitszho @MaxBayne 
Same as #57 , closing.
