### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lnet/vrallev/android/cat/instance/CatLazy;

### ISSUE THREAD

**Issue by gengrui1983** [cloudinary/cloudinary_android#39]
Hi Cloudinary guys

Could anyone please take a look at this error? Looks like something wrong with the Evernote?

Description: After the integration, the app crashes at MediaManager.init(this, config).
The crash happens on both Emulator and phone.

Phone: Nexus 5, Android 5.1.1, API 22
Emulator: Nexus 5X Android 8.0.0, API 26 O
The logs and dependencies are listed as below.
minSdkVersion = 19 
targetSdkVersion = 26
compileSdkVersion = 26
buildToolsVersion = '26.0.2'
gradleVersion = '3.0.0-beta7'

```
class App : Application() {

    @Inject
    lateinit var appLifecycleObserver: AppLifecycleObserver

    override fun onCreate() {
        super.onCreate()
        instance = this

        val config = HashMap<String, String>()
        config.put("cloud_name", "xxxx")
        MediaManager.init(this, config) // <-- Crashes here

        DaggerAppComponent
                .builder()
                .application(this)
                .build()
                .inject(this)

        ProcessLifecycleOwner.get().lifecycle.addObserver(appLifecycleObserver)
    }

    override fun attachBaseContext(base: Context?) {
        super.attachBaseContext(base)

        MultiDex.install(this)
    }

    companion object {
        lateinit var instance: App
            private set
    }
}
```
And the logs are:
```
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: Installing application
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.evernote.android.job.util.JobCat>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/vrallev/android/cat/instance/CatLazy;
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.vrallev.android.cat.instance.CatLazy" on path: DexPathList[[zip file "/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/lib/x86, /data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.evernote.android.job.util.JobCat>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/vrallev/android/cat/instance/CatLazy;
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.vrallev.android.cat.instance.CatLazy" on path: DexPathList[[zip file "/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/lib/x86, /data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.evernote.android.job.util.JobCat>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/vrallev/android/cat/instance/CatLazy;
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.vrallev.android.cat.instance.CatLazy" on path: DexPathList[[zip file "/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/lib/x86, /data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.evernote.android.job.util.JobCat>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/vrallev/android/cat/instance/CatLazy;
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "net.vrallev.android.cat.instance.CatLazy" on path: DexPathList[[zip file "/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/lib/x86, /data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.evernote.android.job.JobManager com.evernote.android.job.JobManager.create(android.content.Context) (JobManager.java:97)
I/zygote:     at void com.cloudinary.android.AndroidJobStrategy.init(android.content.Context) (AndroidJobStrategy.java:82)
I/zygote:     at void com.cloudinary.android.MediaManager.<init>(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:58)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, com.cloudinary.android.signed.SignatureProvider, java.util.Map) (MediaManager.java:159)
I/zygote:     at void com.cloudinary.android.MediaManager.init(android.content.Context, java.util.Map) (MediaManager.java:115)
I/zygote:     at void com.rsvp.babble.App.onCreate() (App.kt:24)
I/zygote:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1118)
I/zygote:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5791)
I/zygote:     at void android.app.ActivityThread.-wrap1(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1661)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
D/AndroidRuntime: Shutting down VM

--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.rsvp.babble, PID: 3381
                  java.lang.NoClassDefFoundError: Failed resolution of: Lnet/vrallev/android/cat/instance/CatLazy;
                      at com.evernote.android.job.JobManager.create(JobManager.java:97)
                      at com.cloudinary.android.AndroidJobStrategy.init(AndroidJobStrategy.java:82)
                      at com.cloudinary.android.MediaManager.<init>(MediaManager.java:58)
                      at com.cloudinary.android.MediaManager.init(MediaManager.java:159)
                      at com.cloudinary.android.MediaManager.init(MediaManager.java:115)
                      at com.rsvp.babble.App.onCreate(App.kt:24)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "net.vrallev.android.cat.instance.CatLazy" on path: DexPathList[[zip file "/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/lib/x86, /data/app/com.rsvp.babble-gG1P7_kClRbJMSvmTTUMOw==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.evernote.android.job.JobManager.create(JobManager.java:97) 
                      at com.cloudinary.android.AndroidJobStrategy.init(AndroidJobStrategy.java:82) 
                      at com.cloudinary.android.MediaManager.<init>(MediaManager.java:58) 
                      at com.cloudinary.android.MediaManager.init(MediaManager.java:159) 
                      at com.cloudinary.android.MediaManager.init(MediaManager.java:115) 
                      at com.rsvp.babble.App.onCreate(App.kt:24) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
                      at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
Application terminated.
```
Dependencies are:
```
dependencies {
    // App's dependencies, including testing
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.android.support:appcompat-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support.constraint:constraint-layout:$rootProject.constraintLayoutVersion"
    implementation "com.android.support:design:$rootProject.supportLibraryVersion"
    implementation "com.android.support:recyclerview-v7:$rootProject.supportLibraryVersion"
    implementation "com.android.support:support-v4:$rootProject.supportLibraryVersion"
    implementation "com.google.guava:guava:$rootProject.guavaVersion"
    implementation "android.arch.lifecycle:extensions:$rootProject.archLifecycleVersion"
    kapt "android.arch.lifecycle:compiler:$rootProject.archLifecycleVersion"

    // Google APIs
    implementation "com.google.android.gms:play-services-location:$rootProject.googleApiVersion"

    // Firebase
    implementation "com.firebase:firebase-jobdispatcher:$rootProject.firebaseJobDispatcherVersion"

    // Kotlin
    implementation "org.jetbrains.anko:anko-common:$rootProject.ankoVersion"
    implementation "org.jetbrains.anko:anko-support-v4-commons:$rootProject.ankoVersion"
    implementation "io.reactivex.rxjava2:rxkotlin:$rootProject.rxkotlinVersion"

    // Retrofit
    implementation "com.squareup.retrofit2:retrofit:$rootProject.retrofitVersion"
    implementation "com.squareup.retrofit2:converter-moshi:$rootProject.retrofitVersion"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$rootProject.retrofitVersion"

    // RxAndroid
    implementation "io.reactivex.rxjava2:rxandroid:$rootProject.rxAndroidVersion"

    // Socket.io
    implementation ("io.socket:socket.io-client:$rootProject.socketIoVersion") {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }

    implementation "de.hdodenhof:circleimageview:$rootProject.circleImageViewVersion"

    // Dagger 2
    implementation "com.google.dagger:dagger:$rootProject.daggerVersion"
    kapt "com.google.dagger:dagger-compiler:$rootProject.daggerVersion"

    compile "com.google.dagger:dagger-android:$project.daggerVersion"
    kapt "com.google.dagger:dagger-android-processor:$project.daggerVersion"

    provided "org.glassfish:javax.annotation:$rootProject.javaxAnnotationVersion"

    // Glide
    implementation "com.github.bumptech.glide:glide:$rootProject.glideVersion"

    // GPU Image
    implementation "jp.co.cyberagent.android.gpuimage:gpuimage-library:$rootProject.gpuImageVersion"

    // Multi Dex
    implementation "com.android.support:multidex:$rootProject.multiDexVersion"

    compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.21.0'

    // Dependencies for local unit tests
    testCompile "junit:junit:$rootProject.ext.junitVersion"
    testCompile "org.mockito:mockito-core:$rootProject.ext.mockitoVersion"
    testCompile "org.hamcrest:hamcrest-all:$rootProject.ext.hamcrestVersion"

    testCompile "android.arch.core:core-testing:$rootProject.archLifecycleVersion"

    // Android Testing Support Library's runner and rules
    androidTestCompile "com.android.support.test:runner:$rootProject.ext.runnerVersion"
    androidTestCompile "com.android.support.test:rules:$rootProject.ext.rulesVersion"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    // Dependencies for Android unit tests
    androidTestCompile "junit:junit:$rootProject.ext.junitVersion"
    androidTestCompile "org.mockito:mockito-android:$rootProject.ext.mockitoVersion"

    // Espresso UI Testing
    androidTestCompile "com.android.support.test.espresso:espresso-core:$rootProject.espressoVersion"
    androidTestCompile "com.android.support.test.espresso:espresso-contrib:$rootProject.espressoVersion"
    androidTestCompile "com.android.support.test.espresso:espresso-intents:$rootProject.espressoVersion"
    androidTestCompile "com.android.support.test.espresso.idling:idling-concurrent:$rootProject.espressoVersion"
    implementation "com.android.support.test.espresso:espresso-idling-resource:$rootProject.espressoVersion"

    // Resolve conflicts between main and test APK:
    androidTestCompile "com.android.support:support-annotations:$rootProject.supportLibraryVersion"
    androidTestCompile "com.android.support:support-v4:$rootProject.supportLibraryVersion"
    androidTestCompile "com.android.support:recyclerview-v7:$rootProject.supportLibraryVersion"
    androidTestCompile "com.android.support:appcompat-v7:$rootProject.supportLibraryVersion"
    androidTestCompile "com.android.support:support-compat:$rootProject.supportLibraryVersion"
    androidTestCompile "com.android.support:design:$rootProject.supportLibraryVersion"
    implementation "com.google.code.findbugs:jsr305:3.0.2"
    kapt "com.android.databinding:compiler:$databindingVersion"
}

// <---gradle of Project --->
ext {
    // Sdk and tools
    minSdkVersion = 19
    targetSdkVersion = 26
    compileSdkVersion = 26
    buildToolsVersion = '26.0.2'

    // App dependencies
    supportLibraryVersion = '27.0.0'
    guavaVersion = '22.0-android'
    junitVersion = '4.12'
    mockitoVersion = '2.7.22'
    hamcrestVersion = '1.3'
    runnerVersion = '1.0.0'
    rulesVersion = '1.0.0'
    espressoVersion = '3.0.1'
    constraintLayoutVersion = '1.0.2'
    ankoVersion = '0.10.1'
    daggerVersion = '2.12'
    javaxAnnotationVersion = '10.0-b28'
    rxkotlinVersion = '2.1.0'
    retrofitVersion = '2.3.0'
    rxAndroidVersion = '2.0.1'
    googleApiVersion = '11.6.0'
    firebaseJobDispatcherVersion = '0.8.4'
    socketIoVersion = '1.0.0'
    circleImageViewVersion = '2.2.0'
    recyclerViewVersion = "27.0.0"
    glideVersion = "4.3.1"
    gpuImageVersion = "1.4.1"
    multiDexVersion = '1.0.2'

    // Architecture Components dependencies
    archLifecycleVersion = "1.0.0"
}

buildscript {
    ext.kotlin_version = '1.1.60'
    ext.gradleVersion = '3.0.0-beta7'
    ext.databindingVersion = '2.3.3'
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0-alpha03'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by gengrui1983** [comment]
All is working now. Please ignore it, thank you.
