### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.evernote.android.job.gcm.PlatformGcmService: java.lang.ClassNotFoundException: Didn't find class "com.evernote.android.job.gcm.PlatformGcmService"

### ISSUE THREAD

**Issue by KancerKure** [cloudinary/cloudinary_android#40]
The app is crashing in lower versions after I did an update. 

`at android.app.ActivityThread.handleCreateService(ActivityThread.java:2720)
       at android.app.ActivityThread.access$1900(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5476)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.ClassNotFoundException: Didn't find class "com.evernote.android.job.gcm.PlatformGcmService" on path: DexPathList[[zip file "/data/app/com.example.myproject-8.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.myproject-8, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2717)
       at android.app.ActivityThread.access$1900(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5476)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)`

My full stacktrace

**Comment by roeeba** [comment]
Hi @KancerKure. This seems to relate to Google Play services. There are several reasons this could happen. Can you please share with us the following?

1. Android versions where it crashes. 
2. Do the phones that crash have Play services?
3. What relevant dependencies are you using (Firebase, Play services) - sharing the `build.gradle` file will help.

In the meantime, please also refer to - https://github.com/evernote/android-job/commit/6a5e846a21a5a368c42d8fe2c0413d360572ddf7
While it's not necessary your issue, there's some information there that may explain it.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
