### ISSUE TITLE
Got Execption java.lang.NoClassDefFoundError: Failed resolution of: Lcom/evernote/android/job/JobManager; in MediaManager.init(this); statement

### ISSUE THREAD

**Issue by kaprat** [cloudinary/cloudinary_android#55]
I am getting the below exception in **MediaManager.init(this, config);** statement.

I am using the libraries cloudinary-core-1.14.0.jar and cloudinary-android-1.20.0.aar

My Code Looks Like

**Map config = new HashMap();
        config.put("cloud_name", "mycloudname");
        config.put("api_key", "myapikey");
        config.put("api_secret", "myapisecret");
        MediaManager.init(this, config);**

03-07 12:17:04.001 9719-9719/com.test.ask E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/evernote/android/job/JobManager;
                                                                           at com.cloudinary.android.AndroidJobStrategy.init(AndroidJobStrategy.java:82)
                                                                           at com.cloudinary.android.MediaManager.<init>(MediaManager.java:58)
                                                                           at com.cloudinary.android.MediaManager.init(MediaManager.java:159)
                                                                           at com.cloudinary.android.MediaManager.init(MediaManager.java:115)
                                                                           at com.test.ask.AskQuestionActivity.uploadImageToCloudinary(AskQuestionActivity.java:1587)
                                                                           at com.test.ask.AskQuestionActivity.onClick(AskQuestionActivity.java:1302)
                                                                           at android.view.View.performClick(View.java:4780)
                                                                           at android.view.View$PerformClick.run(View.java:19866)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.evernote.android.job.JobManager" on path: DexPathList[[zip file "/data/app/com.test.ask-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.ask-2/lib/x86, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at com.cloudinary.android.AndroidJobStrategy.init(AndroidJobStrategy.java:82) 
                                                                           at com.cloudinary.android.MediaManager.<init>(MediaManager.java:58) 
                                                                           at com.cloudinary.android.MediaManager.init(MediaManager.java:159) 
                                                                           at com.cloudinary.android.MediaManager.init(MediaManager.java:115) 
                                                                           at com.test.ask.AskQuestionActivity.uploadImageToCloudinary(AskQuestionActivity.java:1587) 
                                                                           at com.test.ask.AskQuestionActivity.onClick(AskQuestionActivity.java:1302) 
                                                                           at android.view.View.performClick(View.java:4780) 
                                                                           at android.view.View$PerformClick.run(View.java:19866) 
                                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                       	Suppressed: java.lang.ClassNotFoundException: com.evernote.android.job.JobManager
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 17 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by yakirp** [comment]
Hi @kaprat,

Could you please share your Gradle dependencies?

Thanks

**Comment by yakirp** [comment]
Hi, 

could you please change this lines:

```
compile files('libs/cloudinary-core-1.14.0.jar')
compile project(':cloudinary-android-1.20.0')
```

To this:
`compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.24.0'`

Please let me know if it works for you.

Best,
Yakir

**Comment by kaprat** [comment]
Thank you @yakirp sir it's working now.
