### ISSUE TITLE
WakeLockUtil.startWakefulService crash

### ISSUE THREAD

**Issue by Jeff11** [cloudinary/cloudinary_android#88]
This issue https://github.com/evernote/android-job/issues/361 happens on 1.3.0-alpha09 without WorkManager.

Only Android 8 is affected
```
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=my.app/com.evernote.android.job.v14.PlatformAlarmServiceExact (has extras) }: app is in background uid UidRecord{7db0c35 u0a139 RCVR bg:+4m29s651ms idle change:uncached procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1571)
       at android.app.ContextImpl.startService(ContextImpl.java:1527)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at com.evernote.android.job.WakeLockUtil.startWakefulService(WakeLockUtil.java:111)
       at com.evernote.android.job.JobProxy$Common.startWakefulService(JobProxy.java:294)
       at com.evernote.android.job.v14.PlatformAlarmReceiver.onReceive(PlatformAlarmReceiver.java:53)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3195)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6530)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:444)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:812)
```

**Comment by aditimadan-Cloudinary** [comment]
Can you please share what Cloudinary related issue are you experiencing and I will be happy to help.

**Comment by Jeff11** [comment]
Whoops, I posted this on the wrong page. This has nothing to do with cloudinary. Sorry.
