### ISSUE TITLE
upload file issue on Android

### ISSUE THREAD

**Issue by julio-cotta-edx** [cloudinary/cloudinary_android#9]
I am unable to upload images to Cloudinary, look at this stack trackes

Android 4.4.4
```JAVA
W/System.err(15266): javax.net.ssl.SSLProtocolException: Write error: ssl=0x76b56d00: Failure in SSL library, usually a protocol error
W/System.err(15266): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/System.err(15266): 	at gyo.write(SourceFile:743)
W/System.err(15266): 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:131)
W/System.err(15266): 	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:231)
W/System.err(15266): 	at com.android.okhttp.internal.http.RetryableOutputStream.writeToSocket(RetryableOutputStream.java:73)
W/System.err(15266): 	at com.android.okhttp.internal.http.HttpTransport.writeRequestBody(HttpTransport.java:112)
W/System.err(15266): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:638)
W/System.err(15266): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
W/System.err(15266): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
W/System.err(15266): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
W/System.err(15266): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
W/System.err(15266): 	at com.cloudinary.Uploader.callApi(Uploader.java:271)
W/System.err(15266): 	at com.cloudinary.Uploader.upload(Uploader.java:79)
W/System.err(15266): 	at $MY_MAIN_PACKAGE.service.CloudinaryUploadImageService.onHandleIntent(CloudinaryUploadImageService.java:31)
W/System.err(15266): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
W/System.err(15266): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(15266): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(15266): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Android 4.3
```JAVA
V/NativeCrypto(29131): Write error: ssl=0x5cc2a780: Failure in SSL library, usually a protocol error
W/System.err(29131): javax.net.ssl.SSLProtocolException: Write error: ssl=0x5cc2a780: Failure in SSL library, usually a protocol error
W/System.err(29131): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/System.err(29131): 	at gyo.write(SourceFile:743)
W/System.err(29131): 	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:231)
W/System.err(29131): 	at libcore.net.http.RetryableOutputStream.writeToSocket(RetryableOutputStream.java:70)
W/System.err(29131): 	at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:820)
W/System.err(29131): 	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
W/System.err(29131): 	at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
W/System.err(29131): 	at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
W/System.err(29131): 	at com.cloudinary.Uploader.callApi(Uploader.java:271)
W/System.err(29131): 	at com.cloudinary.Uploader.upload(Uploader.java:79)
W/System.err(29131): 	at $MY_MAIN_PACKAGE.service.CloudinaryUploadImageService.onHandleIntent(CloudinaryUploadImageService.java:31)
```
I am running the upload using inside an IntentService
```JAVA
new Cloudinary(this).uploader().upload(pictureFilePath, Cloudinary.emptyMap());
```

Any tip?, it seems some problem with the ssl library, but may be something in the server side, right?

**Comment by isdzulqor** [comment]
@julio-cotta-edx Hi,, could you elaborate more detail how you fix it, please? I have a problem like you.
